language: node_js
node_js:
- 14

services:
- docker

# Prétester les installations
install:
- echo "nothing needs to be installed"

# Scripts à exécuter en guise de tests
before_script:
- echo "no tests"

script:
- docker --version # print the version for logging
- docker-compose --version # Docker compose version for logging
- docker-compose -f docker-compose-build.yaml build --parallel
- docker tag reverseproxy mmkmou/reverseproxy:latest
- docker tag udagram-api-user mmkmou/udagram-api-user:latest
- docker tag udagram-api-feed mmkmou/udagram-api-feed:latest
- docker tag udagram-frontend:local mmkmou/udagram-frontend:latest


after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push mmkmou/simple-node
- docker push mmkmou/reverseproxy:latest
- docker push mmkmou/udagram-api-user:latest
- docker push mmkmou/udagram-api-feed:latest
- docker push mmkmou/udagram-frontend:latest