apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-api-feed
  name: backend-feed
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: udagram-api-feed
  type: ClusterIP
