apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-reverseproxy
  name: publicproxy
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: udagram-reverseproxy
  type: LoadBalancer
status:
  loadBalancer: {}
